spring:
  sql:
    init:
      platform: sqlserver
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;DatabaseName=text
    #开启sql重写
#    url: jdbc:sqlserver://localhost;DatabaseName=text;rewriteBatchedStatements=true
    username: sa
    password: admin1552412358
    #使用连接池
    type: com.alibaba.druid.pool.DruidDataSource
    max-active: 30 #最大连接池数量
    initial-size: 20 #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
    # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，
    # 并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
    max-wait: 60000
    min-idle: 10 #连接池最小空闲数量
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


mybatis-plus:
  #  configuration:
  #    showSql
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      schema: "[text].[easy-excel-test]"
  mapper-locations: [ "classpath*:/xml/*.xml" ]